In [1]:
import warnings
import numpy as np
import os.path as osp

import torch
from torch.utils.data import Dataset
import h5py
import os
import pickle
import copy

data = h5py.File(osp.join("/home/mafzhang/data/PRE/8d/modis_chla_8d_4km_pre.mat"))
chla = np.array(data["CHLA_pre"])
print(np.isnan(chla))
is_sea = np.sum(~np.isnan(chla), 0) >0

[[[ True  True  True ...  True  True  True]
  [ True  True  True ...  True  True  True]
  [ True  True  True ...  True  True  True]
  ...
  [False False False ... False False False]
  [False False False ... False False False]
  [False False False ... False False False]]

 [[ True  True  True ...  True  True  True]
  [ True  True  True ...  True  True  True]
  [ True  True  True ...  True  True  True]
  ...
  [ True  True  True ... False False False]
  [ True  True  True ... False False False]
  [ True  True  True ... False False False]]

 [[ True  True  True ...  True  True  True]
  [ True  True  True ...  True  True  True]
  [ True  True  True ...  True  True  True]
  ...
  [ True  True  True ... False False False]
  [ True  True  True ... False False False]
  [ True  True  True ... False False False]]

 ...

 [[ True  True  True ...  True  True  True]
  [ True  True  True ...  True  True  True]
  [ True  True  True ...  True  True  True]
  ...
  [ True  True  True ...  True  True  Tr

In [2]:
all_area_type = np.zeros((60,96))
area_type = np.load("/home/mafzhang/data/PRE/8d/node_type.npy")
all_area_type[is_sea.astype(bool)] = area_type

In [3]:
# area 1
area1_mask = np.bitwise_and(is_sea, all_area_type==0)
n_nodes = np.sum(area1_mask)

index = np.zeros((60,96))
index[area1_mask] = np.arange(1, np.sum(area1_mask)+1)

source = []
target = []

for i in range(60):
    for j in range(96):
        if area1_mask[i, j]:
            source.append(index[i,j]-1)
            target.append(index[i,j]-1)
            if i>0 and is_sea[i-1, j]:
                source.append(index[i, j] - 1)
                target.append(index[i-1, j] - 1)
            if i<59 and is_sea[i+1, j]:
                source.append(index[i, j] - 1)
                target.append(index[i+1, j] - 1)
            if j>0 and is_sea[i, j-1]:
                source.append(index[i, j] - 1)
                target.append(index[i, j-1] - 1)
            if j<95 and is_sea[i, j+1]:
                source.append(index[i, j] - 1)
                target.append(index[i, j+1] - 1)


adj = np.zeros((n_nodes, n_nodes))

for i in range(len(source)):
    s = int(source[i])
    t = int(target[i])
    adj[s,t] = 1
    
print(adj.shape)

np.save("/home/mafzhang/data/PRE/8d/mask1.npy", area1_mask)
np.save("/home/mafzhang/data/PRE/8d/adj1.npy", adj)

(842, 842)


In [4]:
# area 2
area2_mask = np.bitwise_and(is_sea, all_area_type==1)
n_nodes = np.sum(area2_mask)

index = np.zeros((60,96))
index[area2_mask] = np.arange(1, np.sum(area2_mask)+1)

source = []
target = []

for i in range(60):
    for j in range(96):
        if area2_mask[i, j]:
            source.append(index[i,j]-1)
            target.append(index[i,j]-1)
            if i>0 and is_sea[i-1, j]:
                source.append(index[i, j] - 1)
                target.append(index[i-1, j] - 1)
            if i<59 and is_sea[i+1, j]:
                source.append(index[i, j] - 1)
                target.append(index[i+1, j] - 1)
            if j>0 and is_sea[i, j-1]:
                source.append(index[i, j] - 1)
                target.append(index[i, j-1] - 1)
            if j<95 and is_sea[i, j+1]:
                source.append(index[i, j] - 1)
                target.append(index[i, j+1] - 1)


adj = np.zeros((n_nodes, n_nodes))

for i in range(len(source)):
    s = int(source[i])
    t = int(target[i])
    adj[s,t] = 1
    
print(adj.shape)

np.save("/home/mafzhang/data/PRE/8d/mask2.npy", area2_mask)
np.save("/home/mafzhang/data/PRE/8d/adj2.npy", adj)

(1768, 1768)


In [5]:
# area 2
area3_mask = np.bitwise_and(is_sea, all_area_type==2)
n_nodes = np.sum(area3_mask)

index = np.zeros((60,96))
index[area3_mask] = np.arange(1, np.sum(area3_mask)+1)

source = []
target = []

for i in range(60):
    for j in range(96):
        if area3_mask[i, j]:
            source.append(index[i,j]-1)
            target.append(index[i,j]-1)
            if i>0 and is_sea[i-1, j]:
                source.append(index[i, j] - 1)
                target.append(index[i-1, j] - 1)
            if i<59 and is_sea[i+1, j]:
                source.append(index[i, j] - 1)
                target.append(index[i+1, j] - 1)
            if j>0 and is_sea[i, j-1]:
                source.append(index[i, j] - 1)
                target.append(index[i, j-1] - 1)
            if j<95 and is_sea[i, j+1]:
                source.append(index[i, j] - 1)
                target.append(index[i, j+1] - 1)


adj = np.zeros((n_nodes, n_nodes))

for i in range(len(source)):
    s = int(source[i])
    t = int(target[i])
    adj[s,t] = 1
    
print(adj.shape)

np.save("/home/mafzhang/data/PRE/8d/mask3.npy", area3_mask)
np.save("/home/mafzhang/data/PRE/8d/adj3.npy", adj)

(1833, 1833)


In [1]:
import pickle
import numpy as np
with open('/home/mafzhang/data/PRE/8d/missing_0.1_in_12_out_1_1_imputed_graph.pk', "rb") as f:
    datas, _, _, _, _ = pickle.load(
        f
    )
bound = 648 - 12 - 1
tmp = datas[:bound, 0, 0, 0]

mean = []
std = []
for i in range(60):
    for j in range(96):
        a = tmp[:, i, j]
        if len(a[a != 0]) > 0:
            mean.append(np.nanmean(a[a != 0]))
            std.append(np.nanstd(a[a != 0]))
        else:
            mean.append(a[0])
            std.append(1)

mean = np.array(mean).reshape(60,96)
std = np.array(std).reshape(60,96)
std[std<0.1]=1
print(mean)
print(mean.shape)
print(std)
print(std.shape)

[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 ...
 [-0.63264585 -0.6396085  -0.6182957  ... -0.7712666  -0.7933142
  -0.7765752 ]
 [-0.66046715 -0.659171   -0.67059517 ... -0.7875175  -0.794208
  -0.77968556]
 [-0.6441403  -0.67134136 -0.6737431  ... -0.7721245  -0.779992
  -0.7469417 ]]
(60, 96)
[[1.         1.         1.         ... 1.         1.         1.        ]
 [1.         1.         1.         ... 1.         1.         1.        ]
 [1.         1.         1.         ... 1.         1.         1.        ]
 ...
 [0.22388345 0.22902046 0.23297635 ... 0.21997343 0.21598206 0.21767606]
 [0.2184839  0.22877945 0.22581503 ... 0.21138699 0.22100724 0.21677139]
 [0.22041625 0.22133447 0.22307599 ... 0.21572423 0.21405108 0.22717738]]
(60, 96)


In [2]:
np.save("/home/mafzhang/data/PRE/8d/mean.npy", mean)
np.save("/home/mafzhang/data/PRE/8d/std.npy", std)

In [1]:
import pickle
import numpy as np
with open('/home/mafzhang/data/PRE/8d/missing_0.1_in_12_out_1_1_imputed_graph.pk', "rb") as f:
    datas, _, _, _, _ = pickle.load(
        f
    )
bound = 648 - 12 - 1
tmp = datas[:bound, 0, 0, 0]

mean = []
std = []
for i in range(60):
    for j in range(96):
        a = tmp[:, i, j]
        if len(a[a != 0]) > 0:
            mean.append(np.nanmax(a[a != 0]))
            std.append(np.nanmin(a[a != 0]))
        else:
            mean.append(a[0])
            std.append(a[0])

mean = np.array(mean).reshape(60,96)
std = np.array(std).reshape(60,96)
print(mean)
print(mean.shape)
print(std)
print(std.shape)

[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 ...
 [ 0.2018774   0.18980737  0.20210905 ... -0.12240394 -0.11375386
  -0.07099988]
 [ 0.27388746  0.2957365   0.17548133 ... -0.00773383 -0.00791084
  -0.03280468]
 [ 0.27983278  0.32249758  0.25794244 ...  0.06204317  0.06151919
   0.02475979]]
(60, 96)
[[ 0.         0.         0.        ...  0.         0.         0.       ]
 [ 0.         0.         0.        ...  0.         0.         0.       ]
 [ 0.         0.         0.        ...  0.         0.         0.       ]
 ...
 [-1.1780853 -1.1841677 -1.2079403 ... -1.3074199 -1.3074238 -1.2715187]
 [-1.1847672 -1.2007619 -1.2139857 ... -1.2807885 -1.3079257 -1.2993249]
 [-1.1966194 -1.196622  -1.2243806 ... -1.2888811 -1.3079257 -1.2993249]]
(60, 96)


In [2]:
np.save("/home/mafzhang/data/PRE/8d/max.npy", mean)
np.save("/home/mafzhang/data/PRE/8d/min.npy", std)